/*
Alle afspraken die nog lopend zijn krijgen status 2
Er worden 500 Bezoekers toegevoegd
Er worden 500 afspraken toegevoegd
Elk afspraak heeft een random werknemer en startdatum is NOW()
Moest werknemer status 2 hebben krijgt hij GEEN afspraak
OPTIONAL: Moest werknemer bij meerdere bedrijven werken krijgt hij een afspraak bij waar hij al een afspraak heeft


NOTE: Als je weet dat het bestaat kan je 'CALL Groupswork.GenerateBulkAppointments;' oproepen
*/

DROP PROCEDURE IF EXISTS Groupswork.GenerateBulkAppointments;

DELIMITER $$
CREATE procedure Groupswork.GenerateBulkAppointments()
BEGIN

/*Maken van de afspraken zelf*/
  DECLARE MemTotal INT;
  DECLARE ModifiedTotal INT;
  DECLARE cWerknemerBedrijfId INT;
  DECLARE cWerknemerId INT;
  SET MemTotal = (SELECT COUNT(*) FROM Groupswork.Bezoeker);
  SET ModifiedTotal = MemTotal - 500;
  
  
 /*Elk lopend afspraAK naar beeindigd*/
	UPDATE Groupswork.Afspraak SET AfspraakStatusId = 2, EindTijd = NOW() WHERE AfspraakStatusId = 1;
	
/*Invoeren van bezoekers*/
	INSERT INTO Groupswork.Bezoeker
	(ANaam,VNaam, Email,EigenBedrijf) 
	VALUES
	('Browner', 'Jamal','TestMail1@MikroHard.com', 'MikroHard'),
	('Brown', 'Teresa','TestMail2@Mikrosoft.com', 'Mikrosoft'),
	('Vande Man', 'Pan','TestMail3@TechEgg.com', 'TechEgg'),
	('Brow', 'Terry','TestMail4@Mikrosoft.com', 'Mikrosoft'),
	('Clarke', 'Anita','TestMail5@Alphi.com', 'Alphi'),
	('Phelps', 'Victor','TestMail6@Chekje.com', 'C hekje'),
	('Fox', 'Mae','TestMail7@TechEgg.com', 'TechEgg'),
	('Curry', 'Christian','TestMail8@ElectroBVBA.com', 'Electro BVBA'),
	('Rogers', 'Anthony','TestMail9@ketflix.com', 'ketflix'),
	('Price', 'Orville','TestMail10@Mikrosoft.com', 'Mikrosoft'),
	('Clayton', 'Tabitha','TestMail11@Alternate.com', 'Alternate'),
	('Scott', 'Betty','TestMail12@Chekje.com', 'C hekje'),
	('Sharp', 'Elsa','TestMail13@Chekje.com', 'C hekje'),
	('Simpson', 'Virgil','TestMail14@TechEgg.com', 'TechEgg'),
	('White', 'Alexandra','TestMail15@ketflix.com', 'ketflix'),
	('Horton', 'Sophie','TestMail16@Nimbento.com', 'Nimbento'),
	('Estrada', 'Hilda','TestMail17@ElectroBVBA.com', 'Electro BVBA'),
	('Roberts', 'Stewart','TestMail18@Mikrosoft.com', 'Mikrosoft'),
	('Richards', 'Gretchen','TestMail19@Chekje.com', 'C hekje'),
	('Moran', 'Tabitha','TestMail20@Mikrosoft.com', 'Mikrosoft'),
	('Martin', 'Perry','TestMail21@Alphi.com', 'Alphi'),
	('Bryant', 'Samuel','TestMail22@Nimbento.com', 'Nimbento'),
	('Adams', 'Marlene','TestMail23@Alternate.com', 'Alternate'),
	('Medina', 'Virgil','TestMail24@Alternate.com', 'Alternate'),
	('Anderson', 'Trevor','TestMail25@Chekje.com', 'C hekje'),
	('King', 'Kyle','TestMail26@Nimbento.com', 'Nimbento'),
	('Phelps', 'Katie','TestMail27@TechEgg.com', 'TechEgg'),
	('Scott', 'Angela','TestMail28@FakeBook.com', 'FakeBook'),
	('Fox', 'Emilio','TestMail29@FakeBook.com', 'FakeBook'),
	('Clayton', 'Steven','TestMail30@Mikrosoft.com', 'Mikrosoft'),
	('Tucker', 'Ken','TestMail31@Nimbento.com', 'Nimbento'),
	('Foster', 'Fred','TestMail32@TechEgg.com', 'TechEgg'),
	('Carpenter', 'Mary','TestMail33@Nimbento.com', 'Nimbento'),
	('Hernandez', 'Susie','TestMail34@ketflix.com', 'ketflix'),
	('Herrera', 'Gretchen','TestMail35@Snoogle.com', 'Snoogle'),
	('Fitzgerald', 'Edwin','TestMail36@Alternate.com', 'Alternate'),
	('Hawkins', 'Jasmine','TestMail37@Chekje.com', 'C hekje'),
	('Hart', 'Edwin','TestMail38@Nimbento.com', 'Nimbento'),
	('Hawkins', 'Angela','TestMail39@Nimbento.com', 'Nimbento'),
	('Black', 'Shelia','TestMail40@FakeBook.com', 'FakeBook'),
	('Black', 'Katie','TestMail41@FakeBook.com', 'FakeBook'),
	('Jenkins', 'Ted','TestMail42@FakeBook.com', 'FakeBook'),
	('Coleman', 'Gilberto','TestMail43@ketflix.com', 'ketflix'),
	('Erickson', 'Katie','TestMail44@TechEgg.com', 'TechEgg'),
	('Roberts', 'Fred','TestMail45@Mikrosoft.com', 'Mikrosoft'),
	('Franklin', 'Maggie','TestMail46@FakeBook.com', 'FakeBook'),
	('Bryant', 'Edward','TestMail47@TechEgg.com', 'TechEgg'),
	('Alvarez', 'Wayne','TestMail48@Alternate.com', 'Alternate'),
	('Matthews', 'Lela','TestMail49@FakeBook.com', 'FakeBook'),
	('Jimenez', 'Teresa','TestMail50@TechEgg.com', 'TechEgg'),
	('Meyer', 'Cheryl','TestMail51@Alternate.com', 'Alternate'),
	('Davidson', 'Sonja','TestMail52@Snoogle.com', 'Snoogle'),
	('Davidson', 'Dawn','TestMail53@Mikrosoft.com', 'Mikrosoft'),
	('Oliver', 'Trevor','TestMail54@ElectroBVBA.com', 'Electro BVBA'),
	('Graham', 'Manuel','TestMail55@Alternate.com', 'Alternate'),
	('Schwartz', 'Boyd','TestMail56@ElectroBVBA.com', 'Electro BVBA'),
	('Owens', 'Veronica','TestMail57@FakeBook.com', 'FakeBook'),
	('Parks', 'Hugh','TestMail58@Mikrosoft.com', 'Mikrosoft'),
	('Mcbride', 'Marlene','TestMail59@Alternate.com', 'Alternate'),
	('Franklin', 'Susie','TestMail60@Nimbento.com', 'Nimbento'),
	('Scott', 'Oliver','TestMail61@Alternate.com', 'Alternate'),
	('Fowler', 'Priscilla','TestMail62@Chekje.com', 'C hekje'),
	('Bryant', 'Velma','TestMail63@Snoogle.com', 'Snoogle'),
	('White', 'Virgil','TestMail64@Snoogle.com', 'Snoogle'),
	('Jimenez', 'Jeffrey','TestMail65@TechEgg.com', 'TechEgg'),
	('Price', 'Wayne','TestMail66@TechEgg.com', 'TechEgg'),
	('Hicks', 'Anita','TestMail67@TechEgg.com', 'TechEgg'),
	('Brown', 'Colin','TestMail68@Snoogle.com', 'Snoogle'),
	('Black', 'Sharon','TestMail69@Chekje.com', 'C hekje'),
	('Webster', 'Cheryl','TestMail70@Nimbento.com', 'Nimbento'),
	('Hubbard', 'Candice','TestMail71@TechEgg.com', 'TechEgg'),
	('Hubbard', 'Tami','TestMail72@Snoogle.com', 'Snoogle'),
	('Mendez', 'Anthony','TestMail73@ElectroBVBA.com', 'Electro BVBA'),
	('Barton', 'Lorenzo','TestMail74@Chekje.com', 'C hekje'),
	('Morales', 'Pearl','TestMail75@Mikrosoft.com', 'Mikrosoft'),
	('Tucker', 'Clifton','TestMail76@ElectroBVBA.com', 'Electro BVBA'),
	('Fowler', 'Lorenzo','TestMail77@TechEgg.com', 'TechEgg'),
	('Day', 'Trevor','TestMail78@Alternate.com', 'Alternate'),
	('Schwartz', 'Kyle','TestMail79@Alternate.com', 'Alternate'),
	('Horton', 'Perry','TestMail80@ElectroBVBA.com', 'Electro BVBA'),
	('Herrera', 'Edward','TestMail81@Mikrosoft.com', 'Mikrosoft'),
	('Price', 'Perry','TestMail82@ElectroBVBA.com', 'Electro BVBA'),
	('Medina', 'Betty','TestMail83@Alternate.com', 'Alternate'),
	('Lloyd', 'Benjamin','TestMail84@Alternate.com', 'Alternate'),
	('Palmer', 'Samuel','TestMail85@Snoogle.com', 'Snoogle'),
	('Mcdonald', 'Jeffrey','TestMail86@FakeBook.com', 'FakeBook'),
	('Reynolds', 'Caleb','TestMail87@Snoogle.com', 'Snoogle'),
	('Ball', 'Melanie','TestMail88@TechEgg.com', 'TechEgg'),
	('Bryant', 'Annette','TestMail89@TechEgg.com', 'TechEgg'),
	('Parsons', 'Christian','TestMail90@Chekje.com', 'C hekje'),
	('Fox', 'Bryant','TestMail91@Alphi.com', 'Alphi'),
	('Fox', 'Oliver','TestMail92@Alphi.com', 'Alphi'),
	('Sharp', 'Ray','TestMail93@Alternate.com', 'Alternate'),
	('Carpenter', 'Maggie','TestMail94@Mikrosoft.com', 'Mikrosoft'),
	('Robertson', 'Anthony','TestMail95@Chekje.com', 'C hekje'),
	('Horton', 'Rebecca','TestMail96@Snoogle.com', 'Snoogle'),
	('Cohen', 'Samantha','TestMail97@Snoogle.com', 'Snoogle'),
	('Briggs', 'Tony','TestMail98@Alphi.com', 'Alphi'),
	('Larson', 'Anthony','TestMail99@ElectroBVBA.com', 'Electro BVBA'),
	('Mcdonald', 'Misty','TestMail100@Alternate.com', 'Alternate'),
	('Hodges', 'Genevieve','TestMail101@Snoogle.com', 'Snoogle'),
	('Mcdaniel', 'Maggie','TestMail102@ketflix.com', 'ketflix'),
	('Robertson', 'Vicky','TestMail103@Snoogle.com', 'Snoogle'),
	('Parks', 'Juana','TestMail104@ElectroBVBA.com', 'Electro BVBA'),
	('Palmer', 'Juana','TestMail105@Alphi.com', 'Alphi'),
	('Bridges', 'Laurence','TestMail106@TechEgg.com', 'TechEgg'),
	('Hughes', 'Rosalie','TestMail107@TechEgg.com', 'TechEgg'),
	('Hines', 'Annette','TestMail108@Alphi.com', 'Alphi'),
	('Hodges', 'Cory','TestMail109@ketflix.com', 'ketflix'),
	('Erickson', 'Juana','TestMail110@Snoogle.com', 'Snoogle'),
	('Vargas', 'Anita','TestMail111@FakeBook.com', 'FakeBook'),
	('Bell', 'Maggie','TestMail112@Mikrosoft.com', 'Mikrosoft'),
	('Daniel', 'Henry','TestMail113@FakeBook.com', 'FakeBook'),
	('Adams', 'Laurence','TestMail114@Chekje.com', 'C hekje'),
	('Estrada', 'Phillip','TestMail115@Chekje.com', 'C hekje'),
	('Leonard', 'Mildred','TestMail116@Alternate.com', 'Alternate'),
	('Graham', 'Orville','TestMail117@Alphi.com', 'Alphi'),
	('Fitzgerald', 'Anita','TestMail118@Mikrosoft.com', 'Mikrosoft'),
	('Jenkins', 'Ruby','TestMail119@Mikrosoft.com', 'Mikrosoft'),
	('Estrada', 'Laurence','TestMail120@Alphi.com', 'Alphi'),
	('Jimenez', 'Sonja','TestMail121@Nimbento.com', 'Nimbento'),
	('Underwood', 'Perry','TestMail122@Alphi.com', 'Alphi'),
	('Matthews', 'Annette','TestMail123@Mikrosoft.com', 'Mikrosoft'),
	('Cunningham', 'Opal','TestMail124@TechEgg.com', 'TechEgg'),
	('Martin', 'Sam','TestMail125@ketflix.com', 'ketflix'),
	('Mendez', 'Samuel','TestMail126@ketflix.com', 'ketflix'),
	('Barton', 'Darnell','TestMail127@ElectroBVBA.com', 'Electro BVBA'),
	('White', 'Clifton','TestMail128@Nimbento.com', 'Nimbento'),
	('Moran', 'Candice','TestMail129@Alphi.com', 'Alphi'),
	('Lawson', 'Brandy','TestMail130@Alphi.com', 'Alphi'),
	('Meyer', 'Manuel','TestMail131@FakeBook.com', 'FakeBook'),
	('Davidson', 'Annette','TestMail132@TechEgg.com', 'TechEgg'),
	('Clarke', 'Estelle','TestMail133@ElectroBVBA.com', 'Electro BVBA'),
	('Fowler', 'Blanca','TestMail134@Chekje.com', 'C hekje'),
	('Roberts', 'Colin','TestMail135@FakeBook.com', 'FakeBook'),
	('Jimenez', 'Genevieve','TestMail136@TechEgg.com', 'TechEgg'),
	('Carpenter', 'Angela','TestMail137@Mikrosoft.com', 'Mikrosoft'),
	('Webster', 'Susie','TestMail138@ElectroBVBA.com', 'Electro BVBA'),
	('Erickson', 'Hilda','TestMail139@TechEgg.com', 'TechEgg'),
	('Maxwell', 'Brandy','TestMail140@ketflix.com', 'ketflix'),
	('Mendez', 'Margaret','TestMail141@FakeBook.com', 'FakeBook'),
	('King', 'Marlene','TestMail142@Nimbento.com', 'Nimbento'),
	('Knight', 'Christian','TestMail143@Alphi.com', 'Alphi'),
	('Meyer', 'Samantha','TestMail144@Chekje.com', 'C hekje'),
	('Fitzgerald', 'Agnes','TestMail145@Alphi.com', 'Alphi'),
	('Page', 'Estelle','TestMail146@Chekje.com', 'C hekje'),
	('Barton', 'Priscilla','TestMail147@TechEgg.com', 'TechEgg'),
	('Roberts', 'Holly','TestMail148@FakeBook.com', 'FakeBook'),
	('Obrien', 'Misty','TestMail149@Alphi.com', 'Alphi'),
	('Phelps', 'Sophie','TestMail150@Nimbento.com', 'Nimbento'),
	('Bridges', 'Mildred','TestMail151@Alternate.com', 'Alternate'),
	('Hines', 'Priscilla','TestMail152@Snoogle.com', 'Snoogle'),
	('Parsons', 'Shelia','TestMail153@Snoogle.com', 'Snoogle'),
	('Estrada', 'Jeffrey','TestMail154@Chekje.com', 'C hekje'),
	('Smith', 'Genevieve','TestMail155@Chekje.com', 'C hekje'),
	('Webster', 'Lawrence','TestMail156@Chekje.com', 'C hekje'),
	('Simpson', 'Orville','TestMail157@ElectroBVBA.com', 'Electro BVBA'),
	('Hawkins', 'Margaret','TestMail158@Alphi.com', 'Alphi'),
	('Simpson', 'Angela','TestMail159@Chekje.com', 'C hekje'),
	('Black', 'Priscilla','TestMail160@FakeBook.com', 'FakeBook'),
	('Price', 'Marcella','TestMail161@Nimbento.com', 'Nimbento'),
	('Cunningham', 'Kyle','TestMail162@Alternate.com', 'Alternate'),
	('Clayton', 'Annette','TestMail163@Mikrosoft.com', 'Mikrosoft'),
	('Lawrence', 'Tony','TestMail164@ElectroBVBA.com', 'Electro BVBA'),
	('Herrera', 'Marlene','TestMail165@ElectroBVBA.com', 'Electro BVBA'),
	('Floyd', 'Agnes','TestMail166@Alternate.com', 'Alternate'),
	('Moran', 'Bradford','TestMail167@ketflix.com', 'ketflix'),
	('Parsons', 'Sharon','TestMail168@Chekje.com', 'C hekje'),
	('Bridges', 'Mamie','TestMail169@Nimbento.com', 'Nimbento'),
	('Stephens', 'Tony','TestMail170@Chekje.com', 'C hekje'),
	('Medina', 'Dolores','TestMail171@Alphi.com', 'Alphi'),
	('Daniel', 'Laurence','TestMail172@Mikrosoft.com', 'Mikrosoft'),
	('Mccoy', 'Dolores','TestMail173@ElectroBVBA.com', 'Electro BVBA'),
	('Lawson', 'Betty','TestMail174@FakeBook.com', 'FakeBook'),
	('Ross', 'Lela','TestMail175@Alphi.com', 'Alphi'),
	('Graham', 'Bryant','TestMail176@ketflix.com', 'ketflix'),
	('Munoz', 'Dolores','TestMail177@Alternate.com', 'Alternate'),
	('Underwood', 'Edwin','TestMail178@ElectroBVBA.com', 'Electro BVBA'),
	('Mcbride', 'Steven','TestMail179@Alphi.com', 'Alphi'),
	('Barton', 'Cheryl','TestMail180@Snoogle.com', 'Snoogle'),
	('King', 'Laurence','TestMail181@FakeBook.com', 'FakeBook'),
	('Fitzgerald', 'Ken','TestMail182@Alphi.com', 'Alphi'),
	('Bridges', 'Agnes','TestMail183@ketflix.com', 'ketflix'),
	('Anderson', 'Benjamin','TestMail184@Alternate.com', 'Alternate'),
	('Hines', 'Priscilla','TestMail185@TechEgg.com', 'TechEgg'),
	('Cohen', 'Edwin','TestMail186@FakeBook.com', 'FakeBook'),
	('Rogers', 'Johnnie','TestMail187@Mikrosoft.com', 'Mikrosoft'),
	('Smith', 'Opal','TestMail188@Nimbento.com', 'Nimbento'),
	('Davidson', 'Phillip','TestMail189@Mikrosoft.com', 'Mikrosoft'),
	('Montgomery', 'Virgil','TestMail190@Alphi.com', 'Alphi'),
	('Meyer', 'Oliver','TestMail191@Mikrosoft.com', 'Mikrosoft'),
	('Webster', 'Margaret','TestMail192@Snoogle.com', 'Snoogle'),
	('Garrett', 'Jasmine','TestMail193@Alphi.com', 'Alphi'),
	('Hill', 'Candice','TestMail194@TechEgg.com', 'TechEgg'),
	('Frazier', 'Anita','TestMail195@FakeBook.com', 'FakeBook'),
	('Medina', 'Estelle','TestMail196@Alternate.com', 'Alternate'),
	('Garrett', 'Darnell','TestMail197@Chekje.com', 'C hekje'),
	('Martin', 'Mary','TestMail198@ElectroBVBA.com', 'Electro BVBA'),
	('Anderson', 'Annette','TestMail199@ElectroBVBA.com', 'Electro BVBA'),
	('Schwartz', 'Candice','TestMail200@Chekje.com', 'C hekje'),
	('Bryant', 'Marcella','TestMail201@Chekje.com', 'C hekje'),
	('Jimenez', 'George','TestMail202@ketflix.com', 'ketflix'),
	('Cohen', 'Velma','TestMail203@Mikrosoft.com', 'Mikrosoft'),
	('Cook', 'Samantha','TestMail204@Snoogle.com', 'Snoogle'),
	('Brown', 'Opal','TestMail205@Alternate.com', 'Alternate'),
	('Schwartz', 'Annette','TestMail206@Alphi.com', 'Alphi'),
	('Briggs', 'Sonja','TestMail207@ketflix.com', 'ketflix'),
	('Hernandez', 'Priscilla','TestMail208@Nimbento.com', 'Nimbento'),
	('Mccoy', 'Rebecca','TestMail209@Nimbento.com', 'Nimbento'),
	('Clarke', 'Mildred','TestMail210@ketflix.com', 'ketflix'),
	('Horton', 'Bradford','TestMail211@TechEgg.com', 'TechEgg'),
	('Underwood', 'Holly','TestMail212@TechEgg.com', 'TechEgg'),
	('Ross', 'Maggie','TestMail213@Mikrosoft.com', 'Mikrosoft'),
	('Hill', 'Teresa','TestMail214@Mikrosoft.com', 'Mikrosoft'),
	('Klein', 'Jasmine','TestMail215@Mikrosoft.com', 'Mikrosoft'),
	('Sharp', 'Mildred','TestMail216@FakeBook.com', 'FakeBook'),
	('Brown', 'Oliver','TestMail217@Nimbento.com', 'Nimbento'),
	('Scott', 'Phillip','TestMail218@ketflix.com', 'ketflix'),
	('Vargas', 'Cory','TestMail219@FakeBook.com', 'FakeBook'),
	('Hart', 'Misty','TestMail220@Alternate.com', 'Alternate'),
	('Carpenter', 'Anthony','TestMail221@Snoogle.com', 'Snoogle'),
	('Hughes', 'Benjamin','TestMail222@Snoogle.com', 'Snoogle'),
	('Klein', 'Hilda','TestMail223@TechEgg.com', 'TechEgg'),
	('Cook', 'Anthony','TestMail224@Chekje.com', 'C hekje'),
	('Curry', 'Lawrence','TestMail225@Alphi.com', 'Alphi'),
	('Fox', 'Edward','TestMail226@Mikrosoft.com', 'Mikrosoft'),
	('Vargas', 'Ken','TestMail227@ketflix.com', 'ketflix'),
	('Clayton', 'Kyle','TestMail228@Mikrosoft.com', 'Mikrosoft'),
	('Reynolds', 'Lawrence','TestMail229@ketflix.com', 'ketflix'),
	('Daniel', 'Velma','TestMail230@Alphi.com', 'Alphi'),
	('Obrien', 'George','TestMail231@FakeBook.com', 'FakeBook'),
	('Fox', 'Juana','TestMail232@FakeBook.com', 'FakeBook'),
	('Maxwell', 'Bradford','TestMail233@Alphi.com', 'Alphi'),
	('Bell', 'Caroline','TestMail234@Alphi.com', 'Alphi'),
	('Parsons', 'Lawrence','TestMail235@Nimbento.com', 'Nimbento'),
	('Carpenter', 'Ken','TestMail236@Nimbento.com', 'Nimbento'),
	('Mccoy', 'Hugh','TestMail237@Nimbento.com', 'Nimbento'),
	('Frazier', 'George','TestMail238@Chekje.com', 'C hekje'),
	('Parks', 'Betty','TestMail239@ketflix.com', 'ketflix'),
	('Hines', 'Annette','TestMail240@TechEgg.com', 'TechEgg'),
	('Knight', 'Benjamin','TestMail241@ketflix.com', 'ketflix'),
	('Lawson', 'Anita','TestMail242@Nimbento.com', 'Nimbento'),
	('Lloyd', 'Sonja','TestMail243@Mikrosoft.com', 'Mikrosoft'),
	('Erickson', 'Victor','TestMail244@Snoogle.com', 'Snoogle'),
	('Knight', 'Samuel','TestMail245@TechEgg.com', 'TechEgg'),
	('Erickson', 'Shelia','TestMail246@ketflix.com', 'ketflix'),
	('Oliver', 'Tami','TestMail247@Chekje.com', 'C hekje'),
	('Bridges', 'Oliver','TestMail248@Nimbento.com', 'Nimbento'),
	('Day', 'Sam','TestMail249@ElectroBVBA.com', 'Electro BVBA'),
	('Scott', 'Ruby','TestMail250@Alternate.com', 'Alternate'),
	('Oliver', 'Ray','TestMail251@FakeBook.com', 'FakeBook'),
	('Brown', 'Lela','TestMail252@FakeBook.com', 'FakeBook'),
	('Cook', 'Samantha','TestMail253@Alphi.com', 'Alphi'),
	('Barton', 'Candice','TestMail254@Mikrosoft.com', 'Mikrosoft'),
	('Gardner', 'Alexandra','TestMail255@ElectroBVBA.com', 'Electro BVBA'),
	('Mcdaniel', 'Margaret','TestMail256@TechEgg.com', 'TechEgg'),
	('Fox', 'Victor','TestMail257@Nimbento.com', 'Nimbento'),
	('Richards', 'Fred','TestMail258@Nimbento.com', 'Nimbento'),
	('Fowler', 'Ray','TestMail259@Alphi.com', 'Alphi'),
	('Reynolds', 'Veronica','TestMail260@Mikrosoft.com', 'Mikrosoft'),
	('Hicks', 'Kelley','TestMail261@Alternate.com', 'Alternate'),
	('Cunningham', 'Clifton','TestMail262@ElectroBVBA.com', 'Electro BVBA'),
	('Clayton', 'Johnnie','TestMail263@ElectroBVBA.com', 'Electro BVBA'),
	('Fowler', 'Phillip','TestMail264@FakeBook.com', 'FakeBook'),
	('Matthews', 'Samuel','TestMail265@Snoogle.com', 'Snoogle'),
	('Hines', 'Mae','TestMail266@ElectroBVBA.com', 'Electro BVBA'),
	('Lloyd', 'Jeffrey','TestMail267@Alphi.com', 'Alphi'),
	('Garrett', 'Darnell','TestMail268@Alternate.com', 'Alternate'),
	('Frazier', 'Misty','TestMail269@Mikrosoft.com', 'Mikrosoft'),
	('Lloyd', 'Colin','TestMail270@Nimbento.com', 'Nimbento'),
	('Barton', 'Phillip','TestMail271@TechEgg.com', 'TechEgg'),
	('Munoz', 'Randolph','TestMail272@TechEgg.com', 'TechEgg'),
	('Turner', 'Randolph','TestMail273@TechEgg.com', 'TechEgg'),
	('Munoz', 'Steven','TestMail274@ElectroBVBA.com', 'Electro BVBA'),
	('Clayton', 'Dawn','TestMail275@ketflix.com', 'ketflix'),
	('Horton', 'Dolores','TestMail276@Nimbento.com', 'Nimbento'),
	('Bryant', 'Cheryl','TestMail277@Snoogle.com', 'Snoogle'),
	('Stephens', 'Edwin','TestMail278@TechEgg.com', 'TechEgg'),
	('Foster', 'Dawn','TestMail279@ElectroBVBA.com', 'Electro BVBA'),
	('Erickson', 'Wayne','TestMail280@Nimbento.com', 'Nimbento'),
	('Maxwell', 'Susie','TestMail281@TechEgg.com', 'TechEgg'),
	('Walsh', 'Randolph','TestMail282@Alternate.com', 'Alternate'),
	('Anderson', 'Ruby','TestMail283@Alternate.com', 'Alternate'),
	('Foster', 'Laurie','TestMail284@Mikrosoft.com', 'Mikrosoft'),
	('Hawkins', 'Anita','TestMail285@Alphi.com', 'Alphi'),
	('Price', 'Veronica','TestMail286@ketflix.com', 'ketflix'),
	('Curry', 'Veronica','TestMail287@ketflix.com', 'ketflix'),
	('Hughes', 'Fred','TestMail288@ketflix.com', 'ketflix'),
	('Parsons', 'George','TestMail289@Chekje.com', 'C hekje'),
	('Morales', 'Caleb','TestMail290@Nimbento.com', 'Nimbento'),
	('Stephens', 'Teresa','TestMail291@ElectroBVBA.com', 'Electro BVBA'),
	('Hubbard', 'Johnnie','TestMail292@Chekje.com', 'C hekje'),
	('Moran', 'Christian','TestMail293@Mikrosoft.com', 'Mikrosoft'),
	('Hernandez', 'Sophie','TestMail294@Snoogle.com', 'Snoogle'),
	('Franklin', 'Holly','TestMail295@Alternate.com', 'Alternate'),
	('Walsh', 'Tony','TestMail296@Alphi.com', 'Alphi'),
	('Price', 'Bryant','TestMail297@ketflix.com', 'ketflix'),
	('Frazier', 'Angela','TestMail298@Snoogle.com', 'Snoogle'),
	('Montgomery', 'Samantha','TestMail299@Nimbento.com', 'Nimbento'),
	('Hart', 'Opal','TestMail300@ketflix.com', 'ketflix'),
	('Bryant', 'Wayne','TestMail301@TechEgg.com', 'TechEgg'),
	('Horton', 'Bradford','TestMail302@ketflix.com', 'ketflix'),
	('Hines', 'Benjamin','TestMail303@Nimbento.com', 'Nimbento'),
	('Hubbard', 'Priscilla','TestMail304@Alphi.com', 'Alphi'),
	('Buchanan', 'Caroline','TestMail305@Alphi.com', 'Alphi'),
	('Jimenez', 'Pearl','TestMail306@ElectroBVBA.com', 'Electro BVBA'),
	('Clarke', 'Anthony','TestMail307@Nimbento.com', 'Nimbento'),
	('Munoz', 'Stewart','TestMail308@ElectroBVBA.com', 'Electro BVBA'),
	('Lloyd', 'Marcella','TestMail309@Nimbento.com', 'Nimbento'),
	('Clayton', 'Teresa','TestMail310@Snoogle.com', 'Snoogle'),
	('Cook', 'Kyle','TestMail311@Nimbento.com', 'Nimbento'),
	('Phelps', 'Mildred','TestMail312@Chekje.com', 'C hekje'),
	('Fox', 'Kelley','TestMail313@Alternate.com', 'Alternate'),
	('Hicks', 'Katie','TestMail314@Nimbento.com', 'Nimbento'),
	('Adams', 'Ruby','TestMail315@TechEgg.com', 'TechEgg'),
	('Daniel', 'Anthony','TestMail316@FakeBook.com', 'FakeBook'),
	('Reynolds', 'Boyd','TestMail317@FakeBook.com', 'FakeBook'),
	('Lawson', 'Betty','TestMail318@Chekje.com', 'C hekje'),
	('Lawson', 'Shelia','TestMail319@Alphi.com', 'Alphi'),
	('Hines', 'Samantha','TestMail320@FakeBook.com', 'FakeBook'),
	('Clarke', 'Marcella','TestMail321@Alternate.com', 'Alternate'),
	('Estrada', 'Brandy','TestMail322@Chekje.com', 'C hekje'),
	('Jenkins', 'Rebecca','TestMail323@Mikrosoft.com', 'Mikrosoft'),
	('Cunningham', 'Sharon','TestMail324@ketflix.com', 'ketflix'),
	('Parsons', 'Veronica','TestMail325@ketflix.com', 'ketflix'),
	('Owens', 'Mamie','TestMail326@ElectroBVBA.com', 'Electro BVBA'),
	('Jenkins', 'Betty','TestMail327@Mikrosoft.com', 'Mikrosoft'),
	('Price', 'Steven','TestMail328@ElectroBVBA.com', 'Electro BVBA'),
	('Larson', 'Ross','TestMail329@ketflix.com', 'ketflix'),
	('Ross', 'Tami','TestMail330@FakeBook.com', 'FakeBook'),
	('Lawson', 'Juana','TestMail331@Alphi.com', 'Alphi'),
	('Mcbride', 'Veronica','TestMail332@TechEgg.com', 'TechEgg'),
	('Richards', 'Katie','TestMail333@FakeBook.com', 'FakeBook'),
	('Reynolds', 'Sharon','TestMail334@Chekje.com', 'C hekje'),
	('Montgomery', 'Boyd','TestMail335@Mikrosoft.com', 'Mikrosoft'),
	('Alvarez', 'Pearl','TestMail336@ElectroBVBA.com', 'Electro BVBA'),
	('Simpson', 'Kelley','TestMail337@Mikrosoft.com', 'Mikrosoft'),
	('Simpson', 'Hilda','TestMail338@TechEgg.com', 'TechEgg'),
	('Larson', 'Ted','TestMail339@Nimbento.com', 'Nimbento'),
	('Parks', 'Opal','TestMail340@FakeBook.com', 'FakeBook'),
	('Oliver', 'Priscilla','TestMail341@Mikrosoft.com', 'Mikrosoft'),
	('Hughes', 'Laurence','TestMail342@ElectroBVBA.com', 'Electro BVBA'),
	('Meyer', 'Maggie','TestMail343@Mikrosoft.com', 'Mikrosoft'),
	('Black', 'Caleb','TestMail344@Nimbento.com', 'Nimbento'),
	('Hodges', 'Samuel','TestMail345@TechEgg.com', 'TechEgg'),
	('Morales', 'Johnnie','TestMail346@ketflix.com', 'ketflix'),
	('Page', 'Samantha','TestMail347@Nimbento.com', 'Nimbento'),
	('Ball', 'Jasmine','TestMail348@TechEgg.com', 'TechEgg'),
	('Mcdaniel', 'Randolph','TestMail349@TechEgg.com', 'TechEgg'),
	('Estrada', 'Susie','TestMail350@TechEgg.com', 'TechEgg'),
	('Cook', 'Tabitha','TestMail351@Nimbento.com', 'Nimbento'),
	('Garrett', 'Holly','TestMail352@ketflix.com', 'ketflix'),
	('Evans', 'Genevieve','TestMail353@ElectroBVBA.com', 'Electro BVBA'),
	('Clayton', 'Juana','TestMail354@Nimbento.com', 'Nimbento'),
	('Herrera', 'Betty','TestMail355@ElectroBVBA.com', 'Electro BVBA'),
	('Vargas', 'Kelley','TestMail356@Chekje.com', 'C hekje'),
	('Ball', 'Edward','TestMail357@Alphi.com', 'Alphi'),
	('Franklin', 'Stewart','TestMail358@TechEgg.com', 'TechEgg'),
	('Brown', 'Margaret','TestMail359@Alternate.com', 'Alternate'),
	('Lawson', 'Tony','TestMail360@ElectroBVBA.com', 'Electro BVBA'),
	('Estrada', 'Jeanette','TestMail361@Alternate.com', 'Alternate'),
	('Ross', 'Christian','TestMail362@Alternate.com', 'Alternate'),
	('Brown', 'Hugh','TestMail363@ketflix.com', 'ketflix'),
	('Jimenez', 'Mae','TestMail364@Alphi.com', 'Alphi'),
	('Horton', 'Candice','TestMail365@FakeBook.com', 'FakeBook'),
	('Reynolds', 'Hugh','TestMail366@ketflix.com', 'ketflix'),
	('Jenkins', 'Rosalie','TestMail367@Snoogle.com', 'Snoogle'),
	('Parks', 'Christian','TestMail368@Alternate.com', 'Alternate'),
	('Hill', 'Marcella','TestMail369@ketflix.com', 'ketflix'),
	('Fitzgerald', 'Benjamin','TestMail370@Snoogle.com', 'Snoogle'),
	('Estrada', 'Gilberto','TestMail371@Alphi.com', 'Alphi'),
	('Lawson', 'Clifton','TestMail372@Chekje.com', 'C hekje'),
	('Hart', 'Orville','TestMail373@Alternate.com', 'Alternate'),
	('Hart', 'Bryant','TestMail374@Nimbento.com', 'Nimbento'),
	('Lloyd', 'Sharon','TestMail375@Snoogle.com', 'Snoogle'),
	('Oliver', 'Johnnie','TestMail376@Nimbento.com', 'Nimbento'),
	('Meyer', 'Boyd','TestMail377@Alphi.com', 'Alphi'),
	('Park', 'Marcella','TestMail378@Nimbento.com', 'Nimbento'),
	('Frazier', 'Bradford','TestMail379@Snoogle.com', 'Snoogle'),
	('Fowler', 'Stewart','TestMail380@TechEgg.com', 'TechEgg'),
	('Evans', 'Orville','TestMail381@Snoogle.com', 'Snoogle'),
	('Coleman', 'Phillip','TestMail382@FakeBook.com', 'FakeBook'),
	('Leonard', 'Jeffrey','TestMail383@ketflix.com', 'ketflix'),
	('Vargas', 'Samantha','TestMail384@Nimbento.com', 'Nimbento'),
	('Lloyd', 'Cheryl','TestMail385@Nimbento.com', 'Nimbento'),
	('Ross', 'Estelle','TestMail386@Alternate.com', 'Alternate'),
	('Phelps', 'Johnnie','TestMail387@FakeBook.com', 'FakeBook'),
	('Owens', 'Annette','TestMail388@Snoogle.com', 'Snoogle'),
	('Matthews', 'Mary','TestMail389@Snoogle.com', 'Snoogle'),
	('King', 'Lawrence','TestMail390@Chekje.com', 'C hekje'),
	('Gardner', 'Maggie','TestMail391@Snoogle.com', 'Snoogle'),
	('Lawson', 'Darnell','TestMail392@ElectroBVBA.com', 'Electro BVBA'),
	('Cook', 'Hugh','TestMail393@Mikrosoft.com', 'Mikrosoft'),
	('Phelps', 'Anthony','TestMail394@ElectroBVBA.com', 'Electro BVBA'),
	('Gardner', 'Anita','TestMail395@Snoogle.com', 'Snoogle'),
	('White', 'Sonja','TestMail396@FakeBook.com', 'FakeBook'),
	('Vargas', 'Boyd','TestMail397@Mikrosoft.com', 'Mikrosoft'),
	('Hernandez', 'Blanca','TestMail398@Snoogle.com', 'Snoogle'),
	('Brown', 'Steven','TestMail399@Chekje.com', 'C hekje'),
	('Ross', 'Lorenzo','TestMail400@ketflix.com', 'ketflix'),
	('Ball', 'Cory','TestMail401@Alphi.com', 'Alphi'),
	('Cook', 'Lawrence','TestMail402@ketflix.com', 'ketflix'),
	('Barton', 'Teresa','TestMail403@Alphi.com', 'Alphi'),
	('Lawrence', 'Clifton','TestMail404@Snoogle.com', 'Snoogle'),
	('Hubbard', 'Anthony','TestMail405@ketflix.com', 'ketflix'),
	('Scott', 'Caleb','TestMail406@Chekje.com', 'C hekje'),
	('Scott', 'Teresa','TestMail407@Chekje.com', 'C hekje'),
	('Tucker', 'George','TestMail408@FakeBook.com', 'FakeBook'),
	('Floyd', 'Priscilla','TestMail409@Snoogle.com', 'Snoogle'),
	('Parsons', 'Annette','TestMail410@TechEgg.com', 'TechEgg'),
	('Oliver', 'Priscilla','TestMail411@TechEgg.com', 'TechEgg'),
	('Leonard', 'Lawrence','TestMail412@Chekje.com', 'C hekje'),
	('Ball', 'Maggie','TestMail413@Chekje.com', 'C hekje'),
	('Underwood', 'Gretchen','TestMail414@Snoogle.com', 'Snoogle'),
	('Foster', 'Katie','TestMail415@FakeBook.com', 'FakeBook'),
	('Lloyd', 'Alexandra','TestMail416@TechEgg.com', 'TechEgg'),
	('Cunningham', 'Trevor','TestMail417@TechEgg.com', 'TechEgg'),
	('Morales', 'Steven','TestMail418@FakeBook.com', 'FakeBook'),
	('Hernandez', 'Dolores','TestMail419@Alternate.com', 'Alternate'),
	('Fitzgerald', 'Maggie','TestMail420@Mikrosoft.com', 'Mikrosoft'),
	('Day', 'Edwin','TestMail421@FakeBook.com', 'FakeBook'),
	('Matthews', 'Benjamin','TestMail422@Alternate.com', 'Alternate'),
	('Buchanan', 'Johnnie','TestMail423@FakeBook.com', 'FakeBook'),
	('Daniel', 'Velma','TestMail424@Nimbento.com', 'Nimbento'),
	('Herrera', 'Anthony','TestMail425@TechEgg.com', 'TechEgg'),
	('Bryant', 'Virgil','TestMail426@TechEgg.com', 'TechEgg'),
	('Garrett', 'Rosalie','TestMail427@FakeBook.com', 'FakeBook'),
	('Mcbride', 'Randolph','TestMail428@Nimbento.com', 'Nimbento'),
	('Webster', 'Annette','TestMail429@Nimbento.com', 'Nimbento'),
	('Franklin', 'Ross','TestMail430@Alternate.com', 'Alternate'),
	('Leonard', 'Randolph','TestMail431@Snoogle.com', 'Snoogle'),
	('Mcdaniel', 'Benjamin','TestMail432@Alternate.com', 'Alternate'),
	('Foster', 'Kelley','TestMail433@FakeBook.com', 'FakeBook'),
	('Graham', 'Samantha','TestMail434@Nimbento.com', 'Nimbento'),
	('Mcbride', 'Susie','TestMail435@Alternate.com', 'Alternate'),
	('Hubbard', 'Darnell','TestMail436@ElectroBVBA.com', 'Electro BVBA'),
	('Palmer', 'Sharon','TestMail437@Mikrosoft.com', 'Mikrosoft'),
	('Hawkins', 'Edward','TestMail438@TechEgg.com', 'TechEgg'),
	('Matthews', 'Velma','TestMail439@Alternate.com', 'Alternate'),
	('Mendez', 'Laurence','TestMail440@Alternate.com', 'Alternate'),
	('Moran', 'Jeffrey','TestMail441@Nimbento.com', 'Nimbento'),
	('Hawkins', 'Ruby','TestMail442@ketflix.com', 'ketflix'),
	('Cook', 'Anthony','TestMail443@Nimbento.com', 'Nimbento'),
	('Lloyd', 'Darnell','TestMail444@FakeBook.com', 'FakeBook'),
	('Brown', 'Mary','TestMail445@ElectroBVBA.com', 'Electro BVBA'),
	('Roberts', 'Genevieve','TestMail446@Mikrosoft.com', 'Mikrosoft'),
	('Moran', 'Jeanette','TestMail447@Snoogle.com', 'Snoogle'),
	('Medina', 'Melanie','TestMail448@ketflix.com', 'ketflix'),
	('Klein', 'Ross','TestMail449@Mikrosoft.com', 'Mikrosoft'),
	('Mcdonald', 'Bryant','TestMail450@Alphi.com', 'Alphi'),
	('Horton', 'Manuel','TestMail451@TechEgg.com', 'TechEgg'),
	('Graham', 'Emilio','TestMail452@Snoogle.com', 'Snoogle'),
	('Lawrence', 'Holly','TestMail453@Nimbento.com', 'Nimbento'),
	('Knight', 'Caroline','TestMail454@Snoogle.com', 'Snoogle'),
	('Coleman', 'Ross','TestMail455@Alternate.com', 'Alternate'),
	('Hart', 'Bradford','TestMail456@Chekje.com', 'C hekje'),
	('Daniel', 'Estelle','TestMail457@Mikrosoft.com', 'Mikrosoft'),
	('Price', 'Annette','TestMail458@FakeBook.com', 'FakeBook'),
	('Adams', 'Fred','TestMail459@ketflix.com', 'ketflix'),
	('Matthews', 'Susie','TestMail460@Mikrosoft.com', 'Mikrosoft'),
	('Hart', 'Laurence','TestMail461@ElectroBVBA.com', 'Electro BVBA'),
	('Foster', 'Cheryl','TestMail462@ketflix.com', 'ketflix'),
	('Meyer', 'Ross','TestMail463@Alphi.com', 'Alphi'),
	('Hernandez', 'Oliver','TestMail464@Mikrosoft.com', 'Mikrosoft'),
	('Jenkins', 'Kyle','TestMail465@Snoogle.com', 'Snoogle'),
	('Curry', 'Randolph','TestMail466@ElectroBVBA.com', 'Electro BVBA'),
	('Meyer', 'Edwin','TestMail467@FakeBook.com', 'FakeBook'),
	('Reynolds', 'Rebecca','TestMail468@ElectroBVBA.com', 'Electro BVBA'),
	('Curry', 'Melanie','TestMail469@FakeBook.com', 'FakeBook'),
	('Larson', 'Betty','TestMail470@ElectroBVBA.com', 'Electro BVBA'),
	('Parsons', 'Shelia','TestMail471@Chekje.com', 'C hekje'),
	('Webster', 'Kyle','TestMail472@ketflix.com', 'ketflix'),
	('Briggs', 'Mae','TestMail473@Chekje.com', 'C hekje'),
	('Jenkins', 'Gilberto','TestMail474@Mikrosoft.com', 'Mikrosoft'),
	('Garrett', 'Cory','TestMail475@Alternate.com', 'Alternate'),
	('Bell', 'Mildred','TestMail476@FakeBook.com', 'FakeBook'),
	('Leonard', 'Johnny','TestMail477@Mikrosoft.com', 'Mikrosoft'),
	('Lawrence', 'Virgil','TestMail478@Chekje.com', 'C hekje'),
	('Evans', 'Mildred','TestMail479@Chekje.com', 'C hekje'),
	('Barton', 'Annette','TestMail480@Mikrosoft.com', 'Mikrosoft'),
	('Munoz', 'Dawn','TestMail481@Snoogle.com', 'Snoogle'),
	('Tucker', 'Victor','TestMail482@Alphi.com', 'Alphi'),
	('Daniel', 'Marcella','TestMail483@ketflix.com', 'ketflix'),
	('Maxwell', 'Virgil','TestMail484@Alternate.com', 'Alternate'),
	('Hicks', 'Laurence','TestMail485@Alphi.com', 'Alphi'),
	('Mcdaniel', 'Darnell','TestMail486@FakeBook.com', 'FakeBook'),
	('Owens', 'Veronica','TestMail487@Chekje.com', 'C hekje'),
	('Alvarez', 'Elsa','TestMail488@Nimbento.com', 'Nimbento'),
	('White', 'Virgil','TestMail489@Snoogle.com', 'Snoogle'),
	('Herrera', 'Phillip','TestMail490@Nimbento.com', 'Nimbento'),
	('Jenkins', 'Betty','TestMail491@ElectroBVBA.com', 'Electro BVBA'),
	('Price', 'Priscilla','TestMail492@Chekje.com', 'C hekje'),
	('Franklin', 'Ray','TestMail493@Alternate.com', 'Alternate'),
	('Sharp', 'Steven','TestMail494@ketflix.com', 'ketflix'),
	('Franklin', 'Caleb','TestMail495@FakeBook.com', 'FakeBook'),
	('Franklin', 'Phillip','TestMail496@TechEgg.com', 'TechEgg'),
	('Turner', 'Wayne','TestMail497@Mikrosoft.com', 'Mikrosoft'),
	('Richards', 'Randolph','TestMail498@Alternate.com', 'Alternate'),
	('Anderson', 'Juana','TestMail499@Mikrosoft.com', 'Mikrosoft'),
	('Sanderson', 'Buana','TestMail500@Mikrosoft.com', 'Mikrosoft');
  
  label: 
WHILE (ModifiedTotal < MemTotal) DO
	SET cWerknemerBedrijfId = FLOOR(RAND()*((SELECT COUNT(*) FROM Groupswork.WerknemerBedrijf))+1);
	IF((SELECT COUNT(*) FROM Groupswork.WerknemerBedrijf WHERE Id = cWerknemerBedrijfId AND Status = 1) = 0) THEN
		ITERATE label;
	END	IF;
	/*
	SET cWerknemerId = (SELECT wb.WerknemerId FROM Groupswork.Werknemerbedrijf wb WHERE wb.Id = cWerknemerBedrijfId);
	IF((SELECT COUNT(DISTINCT wb.WerknemerEmail)
		FROM Werknemerbedrijf wb
		JOIN Werknemerbedrijf wbb ON(wb.Id != wbb.Id)
		WHERE wb.WerknemerId = wbb.WerknemerId AND wb.WerknemerId = @WerknemerId) > 1) THEN
			SET cWerknemerBedrijfId =  (SELECT wb.Id
										FROM Werknemerbedrijf wb
										JOIN Werknemerbedrijf wbb ON(wb.Id != wbb.Id)
										WHERE wb.WerknemerId = wbb.WerknemerId AND wb.WerknemerId = cWerknemerId
										ORDER BY (SELECT COUNT(*) FROM Afspraak a WHERE wb.Id = a.WerknemerBedrijfId AND a.AfspraakStatusId = 1) DESC LIMIT 1);
		END	IF;	
		*/
	INSERT INTO Afspraak(StartTijd,WerknemerBedrijfId,BezoekerId )  VALUES(NOW(), cWerknemerBedrijfId, ModifiedTotal);
	SET ModifiedTotal = ModifiedTotal + 1;
  END
WHILE label;
END; $$
DELIMITER ;

CALL Groupswork.GenerateBulkAppointments;