SET GLOBAL event_scheduler = ON;
CREATE EVENT IF NOT EXISTS Groupswork.event_BeeindigAfsprakenSysteem ON SCHEDULE EVERY 1 DAY STARTS TIMESTAMP(
  (CURRENT_DATE + INTERVAL 1 DAY) + INTERVAL 1 MINUTE
) ON COMPLETION PRESERVE DO
UPDATE Groupswork.Afspraak
SET AfspraakStatusId = 4,
  EindTijd = DATE_ADD(
    CONVERT(CONVERT(NOW(), DATE), DATETIME),
    INTERVAL -1 SECOND
  )
WHERE AfspraakStatusId = 1
  AND CONVERT(StartTijd, DATE) < CONVERT(NOW(), DATE);